spring.application.name=club_community_backend

# 연결할 DB URL
spring.datasource.url=${DB_URL}
# DB 유저 이름
spring.datasource.username=${DB_USER}
# DB 비밀번호
spring.datasource.password=${DB_PASSWORD}
# 사용 드라이버
spring.datasource.driver-class-name=org.postgresql.Driver
# 내부에서 동작하는 SQL문 과정을 로그에 보여줄것인지?
spring.jpa.show-sql=true
# SQL문을 잘 다듬어서 보기 좋게 보여주기
spring.jpa.properties.hibernate.format_sql=true
# DB 데이터 변경시 어떻게? - 개발시에는 상관 없으나 실제 구동시 변경
spring.jpa.hibernate.ddl-auto=update
# postgreDB 전용 쿼리 사용할 것을 명시
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 서버를 종료할 때 바로 끄지 않고 '우아하게' 종료함
server.shutdown=graceful
# 서버 종료시 기다릴 시간
spring.lifecycle.timeout-per-shutdown-phase=10s
# DB 커넥션의 최대 생존 시간
spring.datasource.hikari.max-lifetime=1800000
# 커넥션이 아무 일도 안 할 때 반납하는 시간
spring.datasource.hikari.idle-timeout=600000
# 파일 저장을 S3에 할지 로컬에 할지 ( local / s3 )
spring.profiles.active=local
# S3 자동 구성 끄기 및 더미데이터로 설정
spring.cloud.aws.s3.enabled=false
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.credentials.access-key=dummy
spring.cloud.aws.credentials.secret-key=dummy